### ISSUE TITLE
Move meetup data to data files

### ISSUE THREAD

**Issue by dergigi** [valerio-vaccaro/satoshispritz.it#7]
Would it be possible to move the meetup data to [Jekyll data files](https://jekyllrb.com/docs/datafiles/)? (This is a Jekyll site, right?)

This way others could grab it and do stuff with it, e.g. display it on their own map, and so on. It would also DRY[^fn-dry] up the data, as it's duplicate now: one time in the [map data](https://github.com/valerio-vaccaro/satoshispritz.it/blob/main/map.html#L20), and one time in [the table](https://github.com/valerio-vaccaro/satoshispritz.it/blob/main/index.md?plain=1#L21). 

Adding a new data entry would be as easy as creating a file like this:

```yaml
- region: Grosseto
  telegram: https://t.me/SatoshiSpritzToscanaSud
  lat: 42.7628597
  long: 11.1127828
```

...and both the list and the map would update itself automatically.

I'm happy to create a PR myself, but I wanted to check first if it makes sense in your mind as well.

[^fn-dry]: Don't Repeat Yourself
